/*
PIE: CSS3 rendering for IE
Version 1.0beta5-SNAPSHOT
http://css3pie.com
Dual-licensed for use under the Apache License Version 2.0 or the General Public License (GPL) Version 2.
*/
(function(){
var doc = document;var h=window.PIE;
if(!h){h=window.PIE={R:"-pie-",qb:"Pie",nb:"pie_",wc:{TD:1,TH:1},ac:{TABLE:1,THEAD:1,TBODY:1,TFOOT:1,TR:1,INPUT:1,TEXTAREA:1,SELECT:1,OPTION:1,IMG:1,HR:1},ga:function(){}};try{doc.execCommand("BackgroundImageCache",false,true)}catch(ba){}for(var P=4,Q=doc.createElement("div"),R=Q.getElementsByTagName("i"),S;Q.innerHTML="<!--[if gt IE "+ ++P+"]><i></i><![endif]--\>",R[0];);h.ba=P;if(P===6)h.R=h.R.replace(/^-/,"");h.Ba=doc.documentMode||h.ba;Q.innerHTML='<v:shape adj="1"/>';S=Q.firstChild;S.style.behavior=
"url(#default#VML)";h.vc=typeof S.adj==="object";(function(){var a,b=0,c={};h.p={Ya:function(d){if(!a){a=doc.createDocumentFragment();a.namespaces.add("css3vml","urn:schemas-microsoft-com:vml")}return a.createElement("css3vml:"+d)},Aa:function(d){return d&&d._pieId||(d._pieId="_"+ ++b)},Fb:function(d){var e,g,i,j,f=arguments;e=1;for(g=f.length;e<g;e++){j=f[e];for(i in j)if(j.hasOwnProperty(i))d[i]=j[i]}return d},Pb:function(d,e,g){var i=c[d],j,f;if(i)Object.prototype.toString.call(i)==="[object Array]"?
i.push([e,g]):e.call(g,i);else{f=c[d]=[[e,g]];j=new Image;j.onload=function(){i=c[d]={h:j.width,f:j.height};for(var k=0,m=f.length;k<m;k++)f[k][0].call(f[k][1],i);j.onload=null};j.src=d}}}})();h.La={dc:function(a,b,c,d){function e(){k=i>=90&&i<270?b:0;m=i<180?c:0;l=b-k;o=c-m}function g(){for(;i<0;)i+=360;i%=360}var i=d.ta;d=d.Bb;var j,f,k,m,l,o,r,s;if(d){d=d.coords(a,b,c);j=d.x;f=d.y}if(i){i=i.ed();g();e();if(!d){j=k;f=m}d=h.La.oc(j,f,i,l,o);a=d[0];d=d[1]}else if(d){a=b-j;d=c-f}else{j=f=a=0;d=c}r=
a-j;s=d-f;if(i===void 0){i=!r?s<0?90:270:!s?r<0?180:0:-Math.atan2(s,r)/Math.PI*180;g();e()}return{ta:i,tc:j,uc:f,pd:a,qd:d,Sd:k,Td:m,nd:l,od:o,fd:r,gd:s,mc:h.La.bc(j,f,a,d)}},oc:function(a,b,c,d,e){if(c===0||c===180)return[d,b];else if(c===90||c===270)return[a,e];else{c=Math.tan(-c*Math.PI/180);a=c*a-b;b=-1/c;d=b*d-e;e=b-c;return[(d-a)/e,(c*d-b*a)/e]}},bc:function(a,b,c,d){a=c-a;b=d-b;return Math.abs(a===0?b:b===0?a:Math.sqrt(a*a+b*b))}};h.qa=function(){this.Hb=[];this.kc={}};h.qa.prototype={ka:function(a){var b=
h.p.Aa(a),c=this.kc,d=this.Hb;if(!(b in c)){c[b]=d.length;d.push(a)}},ib:function(a){a=h.p.Aa(a);var b=this.kc;if(a&&a in b){delete this.Hb[b[a]];delete b[a]}},ab:function(){for(var a=this.Hb,b=a.length;b--;)a[b]&&a[b]()}};h.Ma=new h.qa;h.Ma.Nd=function(){var a=this;if(!a.Od){setInterval(function(){a.ab()},250);a.Od=1}};h.S=new h.qa;window.attachEvent("onbeforeunload",function(){h.S.ab()});h.S.Ua=function(a,b,c){a.attachEvent(b,c);this.ka(function(){a.detachEvent(b,c)})};(function(){function a(){h.Oa.ab()}
h.Oa=new h.qa;h.S.Ua(window,"onresize",a)})();(function(){function a(){h.pb.ab()}h.pb=new h.qa;h.S.Ua(window,"onscroll",a);h.Oa.ka(a)})();(function(){function a(){c=h.ob.hd()}function b(){if(c){for(var d=0,e=c.length;d<e;d++)h.attach(c[d]);c=0}}var c;h.S.Ua(window,"onbeforeprint",a);h.S.Ua(window,"onafterprint",b)})();h.de=function(){function a(f){this.Z=f}var b=doc.createElement("length-calc"),c=doc.documentElement,d=b.style,e={},g=["mm","cm","in","pt","pc"],i=g.length,j={};d.position="absolute";
d.top=d.left="-9999px";for(c.appendChild(b);i--;){b.style.width="100"+g[i];e[g[i]]=b.offsetWidth/100}c.removeChild(b);b.style.width="1em";a.prototype={Jb:/(px|em|ex|mm|cm|in|pt|pc|%)$/,fc:function(){var f=this.Fd;if(f===void 0)f=this.Fd=parseFloat(this.Z);return f},Ab:function(){var f=this.Xd;if(!f)f=this.Xd=(f=this.Z.match(this.Jb))&&f[0]||"px";return f},a:function(f,k){var m=this.fc(),l=this.Ab();switch(l){case "px":return m;case "%":return m*(typeof k==="function"?k():k)/100;case "em":return m*
this.zb(f);case "ex":return m*this.zb(f)/2;default:return m*e[l]}},zb:function(f){var k=f.currentStyle.fontSize,m,l;if(k.indexOf("px")>0)return parseFloat(k);else if(f.tagName in h.ac){l=this;m=f.parentNode;return h.n(k).a(m,function(){return l.zb(m)})}else{f.appendChild(b);k=b.offsetWidth;b.parentNode===f&&f.removeChild(b);return k}}};h.n=function(f){return j[f]||(j[f]=new a(f))};return a}();h.Ia=function(){function a(e){this.Y=e}var b=h.n("50%"),c={top:1,center:1,bottom:1},d={left:1,center:1,right:1};
a.prototype={vd:function(){if(!this.Zb){var e=this.Y,g=e.length,i=h.v,j=i.ra,f=h.n("0");j=j.na;f=["left",f,"top",f];if(g===1){e.push(new i.rb(j,"center"));g++}if(g===2){j&(e[0].j|e[1].j)&&e[0].d in c&&e[1].d in d&&e.push(e.shift());if(e[0].j&j)if(e[0].d==="center")f[1]=b;else f[0]=e[0].d;else if(e[0].X())f[1]=h.n(e[0].d);if(e[1].j&j)if(e[1].d==="center")f[3]=b;else f[2]=e[1].d;else if(e[1].X())f[3]=h.n(e[1].d)}this.Zb=f}return this.Zb},coords:function(e,g,i){var j=this.vd(),f=j[1].a(e,g);e=j[3].a(e,
i);return{x:j[0]==="right"?g-f:f,y:j[2]==="bottom"?i-e:e}}};return a}();h.Ja=function(){function a(b,c){this.h=b;this.f=c}a.prototype={a:function(b,c,d,e,g){var i=this.h,j=this.f,f=c/d;e=e/g;if(i==="contain"){i=e>f?c:d*e;j=e>f?c/e:d}else if(i==="cover"){i=e<f?c:d*e;j=e<f?c/e:d}else if(i==="auto"){j=j==="auto"?g:j.a(b,d);i=j*e}else{i=i.a(b,c);j=j==="auto"?i/e:j.a(b,d)}return{h:i,f:j}}};a.Gc=new a("auto","auto");return a}();h.Ac=function(){function a(b){this.Z=b}a.prototype={Jb:/[a-z]+$/i,Ab:function(){return this.Xc||
(this.Xc=this.Z.match(this.Jb)[0].toLowerCase())},ed:function(){var b=this.Rc,c;if(b===undefined){b=this.Ab();c=parseFloat(this.Z,10);b=this.Rc=b==="deg"?c:b==="rad"?c/Math.PI*180:b==="grad"?c/400*360:b==="turn"?c*360:0}return b}};return a}();h.Fc=function(){function a(c){this.Z=c}var b={};a.Md=/\s*rgba\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d+|\d*\.\d+)\s*\)\s*/;a.Gb={aliceblue:"F0F8FF",antiquewhite:"FAEBD7",aqua:"0FF",aquamarine:"7FFFD4",azure:"F0FFFF",beige:"F5F5DC",bisque:"FFE4C4",
black:"000",blanchedalmond:"FFEBCD",blue:"00F",blueviolet:"8A2BE2",brown:"A52A2A",burlywood:"DEB887",cadetblue:"5F9EA0",chartreuse:"7FFF00",chocolate:"D2691E",coral:"FF7F50",cornflowerblue:"6495ED",cornsilk:"FFF8DC",crimson:"DC143C",cyan:"0FF",darkblue:"00008B",darkcyan:"008B8B",darkgoldenrod:"B8860B",darkgray:"A9A9A9",darkgreen:"006400",darkkhaki:"BDB76B",darkmagenta:"8B008B",darkolivegreen:"556B2F",darkorange:"FF8C00",darkorchid:"9932CC",darkred:"8B0000",darksalmon:"E9967A",darkseagreen:"8FBC8F",
darkslateblue:"483D8B",darkslategray:"2F4F4F",darkturquoise:"00CED1",darkviolet:"9400D3",deeppink:"FF1493",deepskyblue:"00BFFF",dimgray:"696969",dodgerblue:"1E90FF",firebrick:"B22222",floralwhite:"FFFAF0",forestgreen:"228B22",fuchsia:"F0F",gainsboro:"DCDCDC",ghostwhite:"F8F8FF",gold:"FFD700",goldenrod:"DAA520",gray:"808080",green:"008000",greenyellow:"ADFF2F",honeydew:"F0FFF0",hotpink:"FF69B4",indianred:"CD5C5C",indigo:"4B0082",ivory:"FFFFF0",khaki:"F0E68C",lavender:"E6E6FA",lavenderblush:"FFF0F5",
lawngreen:"7CFC00",lemonchiffon:"FFFACD",lightblue:"ADD8E6",lightcoral:"F08080",lightcyan:"E0FFFF",lightgoldenrodyellow:"FAFAD2",lightgreen:"90EE90",lightgrey:"D3D3D3",lightpink:"FFB6C1",lightsalmon:"FFA07A",lightseagreen:"20B2AA",lightskyblue:"87CEFA",lightslategray:"789",lightsteelblue:"B0C4DE",lightyellow:"FFFFE0",lime:"0F0",limegreen:"32CD32",linen:"FAF0E6",magenta:"F0F",maroon:"800000",mediumauqamarine:"66CDAA",mediumblue:"0000CD",mediumorchid:"BA55D3",mediumpurple:"9370D8",mediumseagreen:"3CB371",
mediumslateblue:"7B68EE",mediumspringgreen:"00FA9A",mediumturquoise:"48D1CC",mediumvioletred:"C71585",midnightblue:"191970",mintcream:"F5FFFA",mistyrose:"FFE4E1",moccasin:"FFE4B5",navajowhite:"FFDEAD",navy:"000080",oldlace:"FDF5E6",olive:"808000",olivedrab:"688E23",orange:"FFA500",orangered:"FF4500",orchid:"DA70D6",palegoldenrod:"EEE8AA",palegreen:"98FB98",paleturquoise:"AFEEEE",palevioletred:"D87093",papayawhip:"FFEFD5",peachpuff:"FFDAB9",peru:"CD853F",pink:"FFC0CB",plum:"DDA0DD",powderblue:"B0E0E6",
purple:"800080",red:"F00",rosybrown:"BC8F8F",royalblue:"4169E1",saddlebrown:"8B4513",salmon:"FA8072",sandybrown:"F4A460",seagreen:"2E8B57",seashell:"FFF5EE",sienna:"A0522D",silver:"C0C0C0",skyblue:"87CEEB",slateblue:"6A5ACD",slategray:"708090",snow:"FFFAFA",springgreen:"00FF7F",steelblue:"4682B4",tan:"D2B48C",teal:"008080",thistle:"D8BFD8",tomato:"FF6347",turquoise:"40E0D0",violet:"EE82EE",wheat:"F5DEB3",white:"FFF",whitesmoke:"F5F5F5",yellow:"FF0",yellowgreen:"9ACD32"};a.prototype={parse:function(){if(!this.Sa){var c=
this.Z,d;if(d=c.match(a.Md)){this.Sa="rgb("+d[1]+","+d[2]+","+d[3]+")";this.Wb=parseFloat(d[4])}else{if((d=c.toLowerCase())in a.Gb)c="#"+a.Gb[d];this.Sa=c;this.Wb=c==="transparent"?0:1}}},V:function(c){this.parse();return this.Sa==="currentColor"?c.currentStyle.color:this.Sa},ea:function(){this.parse();return this.Wb}};h.ha=function(c){return b[c]||(b[c]=new a(c))};return a}();h.v=function(){function a(c){this.Za=c;this.ch=0;this.Y=[];this.Ga=0}var b=a.ra={Ha:1,Ub:2,z:4,Hc:8,Vb:16,na:32,H:64,oa:128,
pa:256,Pa:512,Pc:1024,URL:2048};a.rb=function(c,d){this.j=c;this.d=d};a.rb.prototype={Ca:function(){return this.j&b.H||this.j&b.oa&&this.d==="0"},X:function(){return this.Ca()||this.j&b.Pa}};a.prototype={$d:/\s/,Gd:/^[\+\-]?(\d*\.)?\d+/,url:/^url\(\s*("([^"]*)"|'([^']*)'|([!#$%&*-~]*))\s*\)/i,jc:/^\-?[_a-z][\w-]*/i,Ud:/^("([^"]*)"|'([^']*)')/,xd:/^#([\da-f]{6}|[\da-f]{3})/i,Yd:{px:b.H,em:b.H,ex:b.H,mm:b.H,cm:b.H,"in":b.H,pt:b.H,pc:b.H,deg:b.Ha,rad:b.Ha,grad:b.Ha},bd:{rgb:1,rgba:1,hsl:1,hsla:1},next:function(c){function d(o,
r){o=new a.rb(o,r);if(!c){k.Y.push(o);k.Ga++}return o}function e(){k.Ga++;return null}var g,i,j,f,k=this;if(this.Ga<this.Y.length)return this.Y[this.Ga++];for(;this.$d.test(this.Za.charAt(this.ch));)this.ch++;if(this.ch>=this.Za.length)return e();i=this.ch;g=this.Za.substring(this.ch);j=g.charAt(0);switch(j){case "#":if(f=g.match(this.xd)){this.ch+=f[0].length;return d(b.z,f[0])}break;case '"':case "'":if(f=g.match(this.Ud)){this.ch+=f[0].length;return d(b.Pc,f[2]||f[3]||"")}break;case "/":case ",":this.ch++;
return d(b.pa,j);case "u":if(f=g.match(this.url)){this.ch+=f[0].length;return d(b.URL,f[2]||f[3]||f[4]||"")}}if(f=g.match(this.Gd)){j=f[0];this.ch+=j.length;if(g.charAt(j.length)==="%"){this.ch++;return d(b.Pa,j+"%")}if(f=g.substring(j.length).match(this.jc)){j+=f[0];this.ch+=f[0].length;return d(this.Yd[f[0].toLowerCase()]||b.Hc,j)}return d(b.oa,j)}if(f=g.match(this.jc)){j=f[0];this.ch+=j.length;if(j.toLowerCase()in h.Fc.Gb||j==="currentColor"||j==="transparent")return d(b.z,j);if(g.charAt(j.length)===
"("){this.ch++;if(j.toLowerCase()in this.bd){g=function(o){return o&&o.j&b.oa};f=function(o){return o&&o.j&(b.oa|b.Pa)};var m=function(o,r){return o&&o.d===r},l=function(){return k.next(1)};if((j.charAt(0)==="r"?f(l()):g(l()))&&m(l(),",")&&f(l())&&m(l(),",")&&f(l())&&(j==="rgb"||j==="hsa"||m(l(),",")&&g(l()))&&m(l(),")"))return d(b.z,this.Za.substring(i,this.ch));return e()}return d(b.Vb,j)}return d(b.na,j)}this.ch++;return d(b.Ub,j)},B:function(){return this.Y[this.Ga-- -2]},all:function(){for(;this.next(););
return this.Y},ma:function(c,d){for(var e=[],g,i;g=this.next();){if(c(g)){i=true;this.B();break}e.push(g)}return d&&!i?null:e}};return a}();var V=function(a){this.e=a};V.prototype={$:0,Kd:function(){var a=this.tb,b;return!a||(b=this.o())&&(a.x!==b.x||a.y!==b.y)},Pd:function(){var a=this.tb,b;return!a||(b=this.o())&&(a.h!==b.h||a.f!==b.f)},ec:function(){var a=this.e,b=a.getBoundingClientRect(),c=h.Ba===9;return{x:b.left,y:b.top,h:c?a.offsetWidth:b.right-b.left,f:c?a.offsetHeight:b.bottom-b.top}},o:function(){return this.$?
this.Ta||(this.Ta=this.ec()):this.ec()},wd:function(){return!!this.tb},cb:function(){++this.$},hb:function(){if(!--this.$){if(this.Ta)this.tb=this.Ta;this.Ta=null}}};(function(){function a(b){var c=h.p.Aa(b);return function(){if(this.$){var d=this.Yb||(this.Yb={});return c in d?d[c]:(d[c]=b.call(this))}else return b.call(this)}}h.A={$:0,ja:function(b){function c(d){this.e=d;this.Xb=this.ia()}h.p.Fb(c.prototype,h.A,b);c.Wc={};return c},k:function(){var b=this.ia(),c=this.constructor.Wc;return b?b in
c?c[b]:(c[b]=this.la(b)):null},ia:a(function(){var b=this.e,c=this.constructor,d=b.style;b=b.currentStyle;var e=this.wa,g=this.Fa,i=c.Uc||(c.Uc=h.R+e);c=c.Vc||(c.Vc=h.qb+g.charAt(0).toUpperCase()+g.substring(1));return d[c]||b.getAttribute(i)||d[g]||b.getAttribute(e)}),g:a(function(){return!!this.k()}),F:a(function(){var b=this.ia(),c=b!==this.Xb;this.Xb=b;return c}),va:a,cb:function(){++this.$},hb:function(){--this.$||delete this.Yb}}})();h.Qb=h.A.ja({wa:h.R+"background",Fa:h.qb+"Background",Zc:{scroll:1,
fixed:1,local:1},fb:{"repeat-x":1,"repeat-y":1,repeat:1,"no-repeat":1},nc:{"padding-box":1,"border-box":1,"content-box":1},Ld:{top:1,right:1,bottom:1,left:1,center:1},Qd:{contain:1,cover:1},eb:{Ka:"backgroundClip",z:"backgroundColor",da:"backgroundImage",Na:"backgroundOrigin",T:"backgroundPosition",U:"backgroundRepeat",Qa:"backgroundSize"},la:function(a){function b(t){return t&&t.X()||t.j&k&&t.d in s}function c(t){return t&&(t.X()&&h.n(t.d)||t.d==="auto"&&"auto")}var d=this.e.currentStyle,e,g,i,j=
h.v.ra,f=j.pa,k=j.na,m=j.z,l,o,r=0,s=this.Ld,q,p,v={J:[]};if(this.yb()){e=new h.v(a);for(i={};g=e.next();){l=g.j;o=g.d;if(!i.L&&l&j.Vb&&o==="linear-gradient"){q={ca:[],L:o};for(p={};g=e.next();){l=g.j;o=g.d;if(l&j.Ub&&o===")"){p.color&&q.ca.push(p);q.ca.length>1&&h.p.Fb(i,q);break}if(l&m){if(q.ta||q.Bb){g=e.B();if(g.j!==f)break;e.next()}p={color:h.ha(o)};g=e.next();if(g.X())p.db=h.n(g.d);else e.B()}else if(l&j.Ha&&!q.ta&&!p.color&&!q.ca.length)q.ta=new h.Ac(g.d);else if(b(g)&&!q.Bb&&!p.color&&!q.ca.length){e.B();
q.Bb=new h.Ia(e.ma(function(t){return!b(t)},false))}else if(l&f&&o===","){if(p.color){q.ca.push(p);p={}}}else break}}else if(!i.L&&l&j.URL){i.Cb=o;i.L="image"}else if(b(g)&&!i.aa){e.B();i.aa=new h.Ia(e.ma(function(t){return!b(t)},false))}else if(l&k)if(o in this.fb&&!i.bb)i.bb=o;else if(o in this.nc&&!i.Va){i.Va=o;if((g=e.next())&&g.j&k&&g.d in this.nc)i.wb=g.d;else{i.wb=o;e.B()}}else if(o in this.Zc&&!i.$b)i.$b=o;else return null;else if(l&m&&!v.color)v.color=h.ha(o);else if(l&f&&o==="/"&&!i.Wa&&
i.aa){g=e.next();if(g.j&k&&g.d in this.Qd)i.Wa=new h.Ja(g.d);else if(g=c(g)){l=c(e.next());if(!l){l=g;e.B()}i.Wa=new h.Ja(g,l)}else return null}else if(l&f&&o===","&&i.L){i.Ib=a.substring(r,e.ch-1);r=e.ch;v.J.push(i);i={}}else return null}if(i.L){i.Ib=a.substring(r);v.J.push(i)}}else this.xc(h.Ba<9?function(){var t=this.eb,n=d[t.T+"X"],w=d[t.T+"Y"],x=d[t.da],y=d[t.z];if(y!=="transparent")v.color=h.ha(y);if(x!=="none")v.J=[{L:"image",Cb:(new h.v(x)).next().d,bb:d[t.U],aa:new h.Ia((new h.v(n+" "+w)).all())}]}:
function(){var t=this.eb,n=/\s*,\s*/,w=d[t.da].split(n),x=d[t.z],y,A,u,B,D,C;if(x!=="transparent")v.color=h.ha(x);if((B=w.length)&&w[0]!=="none"){x=d[t.U].split(n);y=d[t.T].split(n);A=d[t.Na].split(n);u=d[t.Ka].split(n);t=d[t.Qa].split(n);v.J=[];for(n=0;n<B;n++)if((D=w[n])&&D!=="none"){C=t[n].split(" ");v.J.push({Ib:D+" "+x[n]+" "+y[n]+" / "+t[n]+" "+A[n]+" "+u[n],L:"image",Cb:(new h.v(D)).next().d,bb:x[n],aa:new h.Ia((new h.v(y[n])).all()),Va:A[n],wb:u[n],Wa:new h.Ja(C[0],C[1])})}}});return v.color||
v.J[0]?v:null},xc:function(a){var b=h.Ba>8,c=this.eb,d=this.e.runtimeStyle,e=d[c.da],g=d[c.z],i=d[c.U],j,f,k,m;if(e)d[c.da]="";if(g)d[c.z]="";if(i)d[c.U]="";if(b){j=d[c.Ka];f=d[c.Na];m=d[c.T];k=d[c.Qa];if(j)d[c.Ka]="";if(f)d[c.Na]="";if(m)d[c.T]="";if(k)d[c.Qa]=""}a=a.call(this);if(e)d[c.da]=e;if(g)d[c.z]=g;if(i)d[c.U]=i;if(b){if(j)d[c.Ka]=j;if(f)d[c.Na]=f;if(m)d[c.T]=m;if(k)d[c.Qa]=k}return a},ia:h.A.va(function(){return this.yb()||this.xc(function(){var a=this.e.currentStyle,b=this.eb;return a[b.z]+
" "+a[b.da]+" "+a[b.U]+" "+a[b.T+"X"]+" "+a[b.T+"Y"]})}),yb:h.A.va(function(){var a=this.e;return a.style[this.Fa]||a.currentStyle.getAttribute(this.wa)}),lc:function(){var a=0;if(h.ba<7){a=this.e;a=""+(a.style[h.qb+"PngFix"]||a.currentStyle.getAttribute(h.R+"png-fix"))==="true"}return a},g:h.A.va(function(){return(this.yb()||this.lc())&&!!this.k()})});h.Tb=h.A.ja({sc:["Top","Right","Bottom","Left"],Ed:{thin:"1px",medium:"3px",thick:"5px"},la:function(){var a={},b={},c={},d=false,e=true,g=true,i=
true;this.yc(function(){for(var j=this.e.currentStyle,f=0,k,m,l,o,r,s,q;f<4;f++){l=this.sc[f];q=l.charAt(0).toLowerCase();k=b[q]=j["border"+l+"Style"];m=j["border"+l+"Color"];l=j["border"+l+"Width"];if(f>0){if(k!==o)g=false;if(m!==r)e=false;if(l!==s)i=false}o=k;r=m;s=l;c[q]=h.ha(m);l=a[q]=h.n(b[q]==="none"?"0":this.Ed[l]||l);if(l.a(this.e)>0)d=true}});return d?{lb:a,Vd:b,cd:c,ae:i,dd:e,Wd:g}:null},ia:h.A.va(function(){var a=this.e,b=a.currentStyle,c;a.tagName in h.wc&&a.offsetParent.currentStyle.borderCollapse===
"collapse"||this.yc(function(){c=b.borderWidth+"|"+b.borderStyle+"|"+b.borderColor});return c}),yc:function(a){var b=this.e.runtimeStyle,c=b.borderWidth,d=b.borderColor;if(c)b.borderWidth="";if(d)b.borderColor="";a=a.call(this);if(c)b.borderWidth=c;if(d)b.borderColor=d;return a}});(function(){h.mb=h.A.ja({wa:"border-radius",Fa:"borderRadius",la:function(b){var c=null,d,e,g,i,j=false;if(b){e=new h.v(b);var f=function(){for(var k=[],m;(g=e.next())&&g.X();){i=h.n(g.d);m=i.fc();if(m<0)return null;if(m>
0)j=true;k.push(i)}return k.length>0&&k.length<5?{tl:k[0],tr:k[1]||k[0],br:k[2]||k[0],bl:k[3]||k[1]||k[0]}:null};if(b=f()){if(g){if(g.j&h.v.ra.pa&&g.d==="/")d=f()}else d=b;if(j&&b&&d)c={x:b,y:d}}}return c}});var a=h.n("0");a={tl:a,tr:a,br:a,bl:a};h.mb.zc={x:a,y:a}})();h.Sb=h.A.ja({wa:"border-image",Fa:"borderImage",fb:{stretch:1,round:1,repeat:1,space:1},la:function(a){var b=null,c,d,e,g,i,j,f=0,k=h.v.ra,m=k.na,l=k.oa,o=k.Pa;if(a){c=new h.v(a);b={};for(var r=function(p){return p&&p.j&k.pa&&p.d===
"/"},s=function(p){return p&&p.j&m&&p.d==="fill"},q=function(){g=c.ma(function(p){return!(p.j&(l|o))});if(s(c.next())&&!b.fill)b.fill=true;else c.B();if(r(c.next())){f++;i=c.ma(function(p){return!p.X()&&!(p.j&m&&p.d==="auto")});if(r(c.next())){f++;j=c.ma(function(p){return!p.Ca()})}}else c.B()};a=c.next();){d=a.j;e=a.d;if(d&(l|o)&&!g){c.B();q()}else if(s(a)&&!b.fill){b.fill=true;q()}else if(d&m&&this.fb[e]&&!b.repeat){b.repeat={f:e};if(a=c.next())if(a.j&m&&this.fb[a.d])b.repeat.kb=a.d;else c.B()}else if(d&
k.URL&&!b.src)b.src=e;else return null}if(!b.src||!g||g.length<1||g.length>4||i&&i.length>4||f===1&&i.length<1||j&&j.length>4||f===2&&j.length<1)return null;if(!b.repeat)b.repeat={f:"stretch"};if(!b.repeat.kb)b.repeat.kb=b.repeat.f;a=function(p,v){return{Q:v(p[0]),P:v(p[1]||p[0]),I:v(p[2]||p[0]),M:v(p[3]||p[1]||p[0])}};b.slice=a(g,function(p){return h.n(p.j&l?p.d+"px":p.d)});if(i&&i[0])b.width=a(i,function(p){return p.X()?h.n(p.d):p.d});if(j&&j[0])b.Da=a(j,function(p){return p.Ca()?h.n(p.d):p.d})}return b}});
h.Ec=h.A.ja({wa:"box-shadow",Fa:"boxShadow",la:function(a){var b,c=h.n,d=h.v.ra,e;if(a){e=new h.v(a);b={Da:[],Db:[]};for(a=function(){for(var g,i,j,f,k,m;g=e.next();){j=g.d;i=g.j;if(i&d.pa&&j===",")break;else if(g.Ca()&&!k){e.B();k=e.ma(function(l){return!l.Ca()})}else if(i&d.z&&!f)f=j;else if(i&d.na&&j==="inset"&&!m)m=true;else return false}g=k&&k.length;if(g>1&&g<5){(m?b.Db:b.Da).push({be:c(k[0].d),ce:c(k[1].d),blur:c(k[2]?k[2].d:"0"),Rd:c(k[3]?k[3].d:"0"),color:h.ha(f||"currentColor")});return true}return false};a(););
}return b&&(b.Db.length||b.Da.length)?b:null}});h.Qc=h.A.ja({ia:h.A.va(function(){var a=this.e.currentStyle;return a.visibility+"|"+a.display}),la:function(){var a=this.e,b=a.runtimeStyle;a=a.currentStyle;var c=b.visibility,d;b.visibility="";d=a.visibility;b.visibility=c;return{Zd:d!=="hidden",jd:a.display!=="none"}},g:function(){return false}});h.u={O:function(a){function b(c,d,e,g){this.e=c;this.s=d;this.i=e;this.parent=g}h.p.Fb(b.prototype,h.u,a);return b},Eb:false,N:function(){return false},Ea:function(){},
Kb:function(){this.m();this.g()&&this.W()},jb:function(){this.Eb=true},Lb:function(){this.g()?this.W():this.m()},vb:function(a,b){this.rc(a);for(var c=this.sa||(this.sa=[]),d=a+1,e=c.length,g;d<e;d++)if(g=c[d])break;c[a]=b;this.G().insertBefore(b,g||null)},ya:function(a){var b=this.sa;return b&&b[a]||null},rc:function(a){var b=this.ya(a),c=this.Ra;if(b&&c){c.removeChild(b);this.sa[a]=null}},za:function(a,b,c,d){var e=this.ub||(this.ub={}),g=e[a];if(!g){g=e[a]=h.p.Ya("shape");if(b)g.appendChild(g[b]=
h.p.Ya(b));if(d){c=this.ya(d);if(!c){this.vb(d,doc.createElement("group"+d));c=this.ya(d)}}c.appendChild(g);a=g.style;a.position="absolute";a.left=a.top=0;a.behavior="url(#default#VML)"}return g},xb:function(a){var b=this.ub,c=b&&b[a];if(c){c.parentNode.removeChild(c);delete b[a]}return!!c},hc:function(a){var b=this.e,c=this.s.o(),d=c.h,e=c.f,g,i,j,f,k,m;c=a.x.tl.a(b,d);g=a.y.tl.a(b,e);i=a.x.tr.a(b,d);j=a.y.tr.a(b,e);f=a.x.br.a(b,d);k=a.y.br.a(b,e);m=a.x.bl.a(b,d);a=a.y.bl.a(b,e);d=Math.min(d/(c+
i),e/(j+k),d/(m+f),e/(g+a));if(d<1){c*=d;g*=d;i*=d;j*=d;f*=d;k*=d;m*=d;a*=d}return{x:{tl:c,tr:i,br:f,bl:m},y:{tl:g,tr:j,br:k,bl:a}}},xa:function(a,b,c){b=b||1;var d,e,g=this.s.o();e=g.h*b;g=g.f*b;var i=this.i.D,j=Math.floor,f=Math.ceil,k=a?a.Q*b:0,m=a?a.P*b:0,l=a?a.I*b:0;a=a?a.M*b:0;var o,r,s,q,p;if(c||i.g()){d=this.hc(c||i.k());c=d.x.tl*b;i=d.y.tl*b;o=d.x.tr*b;r=d.y.tr*b;s=d.x.br*b;q=d.y.br*b;p=d.x.bl*b;b=d.y.bl*b;e="m"+j(a)+","+j(i)+"qy"+j(c)+","+j(k)+"l"+f(e-o)+","+j(k)+"qx"+f(e-m)+","+j(r)+"l"+
f(e-m)+","+f(g-q)+"qy"+f(e-s)+","+f(g-l)+"l"+j(p)+","+f(g-l)+"qx"+j(a)+","+f(g-b)+" x e"}else e="m"+j(a)+","+j(k)+"l"+f(e-m)+","+j(k)+"l"+f(e-m)+","+f(g-l)+"l"+j(a)+","+f(g-l)+"xe";return e},G:function(){var a=this.parent.ya(this.K),b;if(!a){a=doc.createElement(this.Xa);b=a.style;b.position="absolute";b.top=b.left=0;this.parent.vb(this.K,a)}return a},m:function(){this.parent.rc(this.K);delete this.ub;delete this.sa}};h.Nc=h.u.O({g:function(){var a=this.ad;for(var b in a)if(a.hasOwnProperty(b)&&a[b].g())return true;
return false},N:function(){return this.i.Nb.F()},jb:function(){if(this.g()){var a=this.gc(),b=a,c;a=a.currentStyle;var d=a.position,e=this.G().style,g=0,i=0;i=this.s.o();if(d==="fixed"&&h.ba>6){g=i.x;i=i.y;b=d}else{do b=b.offsetParent;while(b&&b.currentStyle.position==="static");if(b){c=b.getBoundingClientRect();b=b.currentStyle;g=i.x-c.left-(parseFloat(b.borderLeftWidth)||0);i=i.y-c.top-(parseFloat(b.borderTopWidth)||0)}else{b=doc.documentElement;g=i.x+b.scrollLeft-b.clientLeft;i=i.y+b.scrollTop-
b.clientTop}b="absolute"}e.position=b;e.left=g;e.top=i;e.zIndex=d==="static"?-1:a.zIndex;this.Eb=true}},Lb:h.ga,Mb:function(){var a=this.i.Nb.k();this.G().style.display=a.Zd&&a.jd?"":"none"},Kb:function(){this.g()?this.Mb():this.m()},gc:function(){var a=this.e;return a.tagName in h.wc?a.offsetParent:a},G:function(){var a=this.Ra,b;if(!a){b=this.gc();a=this.Ra=doc.createElement("css3-container");a.style.direction="ltr";this.Mb();b.parentNode.insertBefore(a,b)}return a},$a:h.ga,m:function(){var a=this.Ra,
b;if(a&&(b=a.parentNode))b.removeChild(a);delete this.Ra;delete this.sa}});h.Bc=h.u.O({K:2,Xa:"background",N:function(){var a=this.i;return a.w.F()||a.D.F()},g:function(){var a=this.i;return a.q.g()||a.D.g()||a.w.g()||a.fa.g()&&a.fa.k().Db},W:function(){var a=this.s.o();if(a.h&&a.f){this.kd();this.ld()}},kd:function(){var a=this.i.w.k(),b=this.s.o(),c=this.e,d=a&&a.color,e,g;if(d&&d.ea()>0){this.ic();a=this.za("bgColor","fill",this.G(),1);e=b.h;b=b.f;a.stroked=false;a.coordsize=e*2+","+b*2;a.coordorigin=
"1,1";a.path=this.xa(null,2);g=a.style;g.width=e;g.height=b;a.fill.color=d.V(c);c=d.ea();if(c<1)a.fill.opacity=c}else this.xb("bgColor")},ld:function(){var a=this.i.w.k(),b=this.s.o();a=a&&a.J;var c,d,e,g,i;if(a){this.ic();d=b.h;e=b.f;for(i=a.length;i--;){b=a[i];c=this.za("bgImage"+i,"fill",this.G(),2);c.stroked=false;c.fill.type="tile";c.fillcolor="none";c.coordsize=d*2+","+e*2;c.coordorigin="1,1";c.path=this.xa(0,2);g=c.style;g.width=d;g.height=e;if(b.L==="linear-gradient")this.Yc(c,b);else{c.fill.src=
b.Cb;this.Jd(c,i)}}}for(i=a?a.length:0;this.xb("bgImage"+i++););},Jd:function(a,b){h.p.Pb(a.fill.src,function(c){var d=a.fill,e=this.e,g=this.s.o(),i=g.h;g=g.f;var j=this.i,f=j.C.k(),k=f&&f.lb;f=k?k.t.a(e):0;var m=k?k.r.a(e):0,l=k?k.b.a(e):0;k=k?k.l.a(e):0;j=j.w.k().J[b];e=j.aa?j.aa.coords(e,i-c.h-k-m,g-c.f-f-l):{x:0,y:0};j=j.bb;l=m=0;var o=i+1,r=g+1,s=h.ba===8?0:1;k=Math.round(e.x)+k+0.5;f=Math.round(e.y)+f+0.5;d.position=k/i+","+f/g;if(j&&j!=="repeat"){if(j==="repeat-x"||j==="no-repeat"){m=f+1;
r=f+c.f+s}if(j==="repeat-y"||j==="no-repeat"){l=k+1;o=k+c.h+s}a.style.clip="rect("+m+"px,"+o+"px,"+r+"px,"+l+"px)"}},this)},Yc:function(a,b){var c=this.e,d=this.s.o(),e=d.h,g=d.f;a=a.fill;d=b.ca;var i=d.length,j=Math.PI,f=h.La,k=f.oc,m=f.bc;b=f.dc(c,e,g,b);f=b.ta;var l=b.tc,o=b.uc,r=b.Sd,s=b.Td,q=b.nd,p=b.od,v=b.fd,t=b.gd;b=b.mc;e=f%90?Math.atan2(v*e/g,t)/j*180:f+90;e+=180;e%=360;q=k(r,s,f,q,p);g=m(r,s,q[0],q[1]);j=[];q=k(l,o,f,r,s);m=m(l,o,q[0],q[1])/g*100;k=[];for(f=0;f<i;f++)k.push(d[f].db?d[f].db.a(c,
b):f===0?0:f===i-1?b:null);for(f=1;f<i;f++){if(k[f]===null){l=k[f-1];b=f;do o=k[++b];while(o===null);k[f]=l+(o-l)/(b-f+1)}k[f]=Math.max(k[f],k[f-1])}for(f=0;f<i;f++)j.push(m+k[f]/g*100+"% "+d[f].color.V(c));a.angle=e;a.type="gradient";a.method="sigma";a.color=d[0].color.V(c);a.color2=d[i-1].color.V(c);a.colors.value=j.join(",")},ic:function(){var a=this.e.runtimeStyle;a.backgroundImage="url(about:blank)";a.backgroundColor="transparent"},m:function(){h.u.m.call(this);var a=this.e.runtimeStyle;a.backgroundImage=
a.backgroundColor=""}});h.Cc=h.u.O({K:4,Xa:"border",Dd:{submit:1,button:1,reset:1},N:function(){var a=this.i;return a.C.F()||a.D.F()},g:function(){var a=this.i;return(a.D.g()||a.w.g())&&!a.q.g()&&a.C.g()},W:function(){var a=this.e,b=this.i.C.k(),c=this.s.o(),d=c.h;c=c.f;var e,g,i,j,f;if(b){this.zd();b=this.sd(2);j=0;for(f=b.length;j<f;j++){i=b[j];e=this.za("borderPiece"+j,i.stroke?"stroke":"fill",this.G());e.coordsize=d*2+","+c*2;e.coordorigin="1,1";e.path=i.path;g=e.style;g.width=d;g.height=c;e.filled=
!!i.fill;e.stroked=!!i.stroke;if(i.stroke){e=e.stroke;e.weight=i.Ob+"px";e.color=i.color.V(a);e.dashstyle=i.stroke==="dashed"?"2 2":i.stroke==="dotted"?"1 1":"solid";e.linestyle=i.stroke==="double"&&i.Ob>2?"ThinThin":"Single"}else e.fill.color=i.fill.V(a)}for(;this.xb("borderPiece"+j++););}},zd:function(){var a=this.e,b=a.currentStyle,c=a.runtimeStyle,d=a.tagName,e=h.ba===6,g;if(e&&(d in h.ac||d==="FIELDSET")||d==="BUTTON"||d==="INPUT"&&a.type in this.Dd){c.borderWidth="";d=this.i.C.sc;for(g=d.length;g--;){e=
d[g];c["padding"+e]="";c["padding"+e]=h.n(b["padding"+e]).a(a)+h.n(b["border"+e+"Width"]).a(a)+(!h.ba===8&&g%2?1:0)}c.borderWidth=0}else if(e){if(a.childNodes.length!==1||a.firstChild.tagName!=="ie6-mask"){b=doc.createElement("ie6-mask");d=b.style;d.visibility="visible";for(d.zoom=1;d=a.firstChild;)b.appendChild(d);a.appendChild(b);c.visibility="hidden"}}else c.borderColor="transparent"},sd:function(a){var b=this.e,c,d,e,g=this.i.C,i=[],j,f,k,m,l=Math.round,o,r,s;if(g.g()){c=g.k();g=c.lb;r=c.Vd;s=
c.cd;if(c.ae&&c.Wd&&c.dd){if(s.t.ea()>0){c=g.t.a(b);k=c/2;i.push({path:this.xa({Q:k,P:k,I:k,M:k},a),stroke:r.t,color:s.t,Ob:c})}}else{a=a||1;c=this.s.o();d=c.h;e=c.f;c=l(g.t.a(b));k=l(g.r.a(b));m=l(g.b.a(b));b=l(g.l.a(b));var q={t:c,r:k,b:m,l:b};b=this.i.D;if(b.g())o=this.hc(b.k());j=Math.floor;f=Math.ceil;var p=function(n,w){return o?o[n][w]:0},v=function(n,w,x,y,A,u){var B=p("x",n),D=p("y",n),C=n.charAt(1)==="r";n=n.charAt(0)==="b";return B>0&&D>0?(u?"al":"ae")+(C?f(d-B):j(B))*a+","+(n?f(e-D):j(D))*
a+","+(j(B)-w)*a+","+(j(D)-x)*a+","+y*65535+","+2949075*(A?1:-1):(u?"m":"l")+(C?d-w:w)*a+","+(n?e-x:x)*a},t=function(n,w,x,y){var A=n==="t"?j(p("x","tl"))*a+","+f(w)*a:n==="r"?f(d-w)*a+","+j(p("y","tr"))*a:n==="b"?f(d-p("x","br"))*a+","+j(e-w)*a:j(w)*a+","+f(e-p("y","bl"))*a;n=n==="t"?f(d-p("x","tr"))*a+","+f(w)*a:n==="r"?f(d-w)*a+","+f(e-p("y","br"))*a:n==="b"?j(p("x","bl"))*a+","+j(e-w)*a:j(w)*a+","+j(p("y","tl"))*a;return x?(y?"m"+n:"")+"l"+A:(y?"m"+A:"")+"l"+n};b=function(n,w,x,y,A,u){var B=n===
"l"||n==="r",D=q[n],C,F;if(D>0&&r[n]!=="none"&&s[n].ea()>0){C=q[B?n:w];w=q[B?w:n];F=q[B?n:x];x=q[B?x:n];if(r[n]==="dashed"||r[n]==="dotted"){i.push({path:v(y,C,w,u+45,0,1)+v(y,0,0,u,1,0),fill:s[n]});i.push({path:t(n,D/2,0,1),stroke:r[n],Ob:D,color:s[n]});i.push({path:v(A,F,x,u,0,1)+v(A,0,0,u-45,1,0),fill:s[n]})}else i.push({path:v(y,C,w,u+45,0,1)+t(n,D,0,0)+v(A,F,x,u,0,0)+(r[n]==="double"&&D>2?v(A,F-j(F/3),x-j(x/3),u-45,1,0)+t(n,f(D/3*2),1,0)+v(y,C-j(C/3),w-j(w/3),u,1,0)+"x "+v(y,j(C/3),j(w/3),u+
45,0,1)+t(n,j(D/3),1,0)+v(A,j(F/3),j(x/3),u,0,0):"")+v(A,0,0,u-45,1,0)+t(n,0,1,0)+v(y,0,0,u,1,0),fill:s[n]})}};b("t","l","r","tl","tr",90);b("r","t","b","tr","br",0);b("b","r","l","br","bl",-90);b("l","b","t","bl","tl",-180)}}return i},m:function(){h.u.m.call(this);if(!this.cc&&!this.i.q.g())this.e.runtimeStyle.borderColor=""}});h.Rb=h.u.O({K:5,Id:["t","tr","r","br","b","bl","l","tl","c"],N:function(){return this.i.q.F()},g:function(){return this.i.q.g()},W:function(){this.G();var a=this.i.q.k(),
b=this.s.o(),c=this.e,d=this.qc;h.p.Pb(a.src,function(e){function g(v,t,n,w,x){v=d[v].style;var y=Math.max;v.width=y(t,0);v.height=y(n,0);v.left=w;v.top=x}function i(v,t,n){for(var w=0,x=v.length;w<x;w++)d[v[w]].imagedata[t]=n}var j=b.h,f=b.f,k=h.n,m=c.currentStyle,l=a.width,o=(l?l.Q:k(m.borderTopWidth)).a(c),r=(l?l.P:k(m.borderRightWidth)).a(c),s=(l?l.I:k(m.borderBottomWidth)).a(c);k=(l?l.M:k(m.borderLeftWidth)).a(c);var q=a.slice;m=q.Q.a(c);l=q.P.a(c);var p=q.I.a(c);q=q.M.a(c);g("tl",k,o,0,0);g("t",
j-k-r,o,k,0);g("tr",r,o,j-r,0);g("r",r,f-o-s,j-r,o);g("br",r,s,j-r,f-s);g("b",j-k-r,s,k,f-s);g("bl",k,s,0,f-s);g("l",k,f-o-s,0,o);g("c",j-k-r,f-o-s,k,o);i(["tl","t","tr"],"cropBottom",(e.f-m)/e.f);i(["tl","l","bl"],"cropRight",(e.h-q)/e.h);i(["bl","b","br"],"cropTop",(e.f-p)/e.f);i(["tr","r","br"],"cropLeft",(e.h-l)/e.h);if(a.repeat.kb==="stretch"){i(["l","r","c"],"cropTop",m/e.f);i(["l","r","c"],"cropBottom",p/e.f)}if(a.repeat.f==="stretch"){i(["t","b","c"],"cropLeft",q/e.h);i(["t","b","c"],"cropRight",
l/e.h)}d.c.style.display=a.fill?"":"none"},this)},G:function(){var a=this.parent.ya(this.K),b,c,d,e=this.Id,g=e.length;if(!a){a=doc.createElement("border-image");b=a.style;b.position="absolute";this.qc={};for(d=0;d<g;d++){c=this.qc[e[d]]=h.p.Ya("rect");c.appendChild(h.p.Ya("imagedata"));b=c.style;b.behavior="url(#default#VML)";b.position="absolute";b.top=b.left=0;c.imagedata.src=this.i.q.k().src;c.stroked=false;c.filled=false;a.appendChild(c)}this.parent.vb(this.K,a)}return a},Ea:function(){if(this.g()){var a=
this.e.runtimeStyle,b=this.e,c=this.i.q.k().width;a.borderColor="transparent";a.borderStyle="solid";if(c){a.borderTopWidth=c.Q.a(b)+"px";a.borderRightWidth=c.P.a(b)+"px";a.borderBottomWidth=c.I.a(b)+"px";a.borderLeftWidth=c.M.a(b)+"px"}}},m:function(){if(!this.cc&&!this.i.C.g()){var a=this.e.runtimeStyle;a.borderColor=a.borderStyle=a.borderWidth=""}}});h.Dc=h.u.O({K:1,Xa:"outset-box-shadow",N:function(){var a=this.i;return a.fa.F()||a.D.F()},g:function(){var a=this.i.fa;return a.g()&&a.k().Da[0]},
W:function(){function a(C,F,J,K,L,I,H){C=b.za("shadow"+C+F,"fill",d,i-C);F=C.fill;C.coordsize=m*2+","+l*2;C.coordorigin="1,1";C.stroked=false;C.filled=true;F.color=L.V(c);if(I){F.type="gradienttitle";F.color2=F.color;F.opacity=0}C.path=H;p=C.style;p.left=J;p.top=K;p.width=m;p.height=l;return C}var b=this,c=this.e,d=this.G(),e=this.i,g=e.fa.k().Da;e=e.D.k();var i=g.length,j=i,f,k=this.s.o(),m=k.h,l=k.f;k=h.ba===8?1:0;for(var o=["tl","tr","br","bl"],r,s,q,p,v,t,n,w,x,y,A,u,B,D;j--;){s=g[j];v=s.be.a(c);
t=s.ce.a(c);f=s.Rd.a(c);n=s.blur.a(c);s=s.color;w=-f-n;if(!e&&n)e=h.mb.zc;w=this.xa({Q:w,P:w,I:w,M:w},2,e);if(n){x=(f+n)*2+m;y=(f+n)*2+l;A=n*2/x;u=n*2/y;if(n-f>m/2||n-f>l/2)for(f=4;f--;){r=o[f];B=r.charAt(0)==="b";D=r.charAt(1)==="r";r=a(j,r,v,t,s,n,w);q=r.fill;q.focusposition=(D?1-A:A)+","+(B?1-u:u);q.focussize="0,0";r.style.clip="rect("+((B?y/2:0)+k)+"px,"+(D?x:x/2)+"px,"+(B?y:y/2)+"px,"+((D?x/2:0)+k)+"px)"}else{r=a(j,"",v,t,s,n,w);q=r.fill;q.focusposition=A+","+u;q.focussize=1-A*2+","+(1-u*2)}}else{r=
a(j,"",v,t,s,n,w);v=s.ea();if(v<1)r.fill.opacity=v}}}});h.Lc=h.u.O({K:6,Xa:"imgEl",N:function(){var a=this.i;return this.e.src!==this.Tc||a.D.F()},g:function(){var a=this.i;return a.D.g()||a.w.lc()},W:function(){this.Tc=i;this.yd();var a=this.za("img","fill",this.G()),b=a.fill,c=this.s.o(),d=c.h;c=c.f;var e=this.i.C.k();e=e&&e.lb;var g=this.e,i=g.src,j=Math.round;a.stroked=false;b.type="frame";b.src=i;b.position=(d?0.5/d:0)+","+(c?0.5/c:0);a.coordsize=d*2+","+c*2;a.coordorigin="1,1";a.path=this.xa(e?
{Q:j(e.t.a(g)),P:j(e.r.a(g)),I:j(e.b.a(g)),M:j(e.l.a(g))}:0,2);a=a.style;a.width=d;a.height=c},yd:function(){this.e.runtimeStyle.filter="alpha(opacity=0)"},m:function(){h.u.m.call(this);this.e.runtimeStyle.filter=""}});h.Kc=h.u.O({jb:h.ga,Lb:h.ga,Mb:h.ga,Kb:h.ga,Hd:/^,+|,+$/g,Cd:/,+/g,gb:function(a,b){(this.sb||(this.sb=[]))[a]=b||void 0},$a:function(){var a=this.sb,b;if(a&&(b=a.join(",").replace(this.Hd,"").replace(this.Cd,","))!==this.Sc)this.Sc=this.e.runtimeStyle.background=b},m:function(){this.e.runtimeStyle.background=
"";delete this.sb}});h.Ic=h.u.O({ua:1,N:function(){return this.i.w.F()},g:function(){var a=this.i;return a.w.g()||a.q.g()},W:function(){var a=this.i.w.k(),b,c,d=0,e,g;if(a){b=[];if(c=a.J)for(;e=c[d++];)if(e.L==="linear-gradient"){g=this.rd(e.Va);g=(e.Wa||h.Ja.Gc).a(this.e,g.h,g.f,g.h,g.f);b.push("url(data:image/svg+xml,"+escape(this.td(e,g.h,g.f))+") "+this.$c(e.aa)+" / "+g.h+"px "+g.f+"px "+(e.$b||"")+" "+(e.Va||"")+" "+(e.wb||""))}else b.push(e.Ib);a.color&&b.push(a.color.Z);this.parent.gb(this.ua,
b.join(","))}},$c:function(a){return a?a.Y.map(function(b){return b.d}).join(" "):"0 0"},rd:function(a){var b=this.e,c=this.s.o(),d=c.h;c=c.f;var e;if(a!=="border-box")if((e=this.i.C.k())&&(e=e.lb)){d-=e.l.a(b)+e.l.a(b);c-=e.t.a(b)+e.b.a(b)}if(a==="content-box"){a=h.n;e=b.currentStyle;d-=a(e.paddingLeft).a(b)+a(e.paddingRight).a(b);c-=a(e.paddingTop).a(b)+a(e.paddingBottom).a(b)}return{h:d,f:c}},td:function(a,b,c){var d=this.e,e=a.ca,g=e.length,i=h.La.dc(d,b,c,a);a=i.tc;var j=i.uc,f=i.pd,k=i.qd;i=
i.mc;var m,l,o,r,s;m=[];for(l=0;l<g;l++)m.push(e[l].db?e[l].db.a(d,i):l===0?0:l===g-1?i:null);for(l=1;l<g;l++)if(m[l]===null){r=m[l-1];o=l;do s=m[++o];while(s===null);m[l]=r+(s-r)/(o-l+1)}b=['<svg width="'+b+'" height="'+c+'" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" gradientUnits="userSpaceOnUse" x1="'+a/b*100+'%" y1="'+j/c*100+'%" x2="'+f/b*100+'%" y2="'+k/c*100+'%">'];for(l=0;l<g;l++)b.push('<stop offset="'+m[l]/i+'" stop-color="'+e[l].color.V(d)+'" stop-opacity="'+e[l].color.ea()+
'"/>');b.push('</linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>');return b.join("")},m:function(){this.parent.gb(this.ua)}});h.Jc=h.u.O({U:"repeat",Oc:"stretch",Mc:"round",ua:0,N:function(){return this.i.q.F()},g:function(){return this.i.q.g()},W:function(){var a=this,b=a.i.q.k(),c=a.s.o(),d=b.repeat,e=d.f,g=d.kb,i=a.e,j=i.currentStyle,f=0;h.p.Pb(b.src,function(k){function m(N,M,O,W,Y,Z,$,aa,T,U){z.push('<pattern patternUnits="userSpaceOnUse" id="pattern'+G+'" x="'+
(e===v?N+O/2-T/2:N)+'" y="'+(g===v?M+W/2-U/2:M)+'" width="'+T+'" height="'+U+'"><svg width="'+T+'" height="'+U+'" viewBox="'+Y+" "+Z+" "+$+" "+aa+'" preserveAspectRatio="none"><image xlink:href="'+p+'" x="0" y="0" width="'+r+'" height="'+s+'" /></svg></pattern>');E.push('<rect x="'+N+'" y="'+M+'" width="'+O+'" height="'+W+'" fill="url(#pattern'+G+')" />');G++}var l=c.h,o=c.f,r=k.h,s=k.f,q=h.n,p=a.Ad(b.src,r,s),v=a.U,t=a.Oc,n=a.Mc,w=Math.ceil,x=b.width;k=(x?x.Q:q(j.borderTopWidth)).a(i);var y=(x?x.P:
q(j.borderRightWidth)).a(i),A=(x?x.I:q(j.borderBottomWidth)).a(i);q=(x?x.M:q(j.borderLeftWidth)).a(i);var u=b.slice;x=u.Q.a(i);var B=u.P.a(i),D=u.I.a(i);u=u.M.a(i);var C=l-q-y,F=o-k-A,J=r-u-B,K=s-x-D,L=e===t?C:J*k/x,I=g===t?F:K*y/B,H=e===t?C:J*A/D;t=g===t?F:K*q/u;var z=[],E=[],G=0;if(e===n){L-=(L-(C%L||L))/w(C/L);H-=(H-(C%H||H))/w(C/H)}if(g===n){I-=(I-(F%I||I))/w(F/I);t-=(t-(F%t||t))/w(F/t)}n=['<svg width="'+l+'" height="'+o+'" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">'];
m(0,0,q,k,0,0,u,x,q,k);m(q,0,C,k,u,0,J,x,L,k);m(l-y,0,y,k,r-B,0,B,x,y,k);m(0,k,q,F,0,x,u,K,q,t);if(b.fill)m(q,k,C,F,u,x,J,K,L||H||J,t||I||K);m(l-y,k,y,F,r-B,x,B,K,y,I);m(0,o-A,q,A,0,s-D,u,D,q,A);m(q,o-A,C,A,u,s-D,J,D,H,A);m(l-y,o-A,y,A,r-B,s-D,B,D,y,A);n.push("<defs>"+z.join("\n")+"</defs>"+E.join("\n")+"</svg>");a.parent.gb(a.ua,"url(data:image/svg+xml,"+escape(n.join(""))+") no-repeat border-box border-box");f&&a.parent.$a()},a);f=1},Ad:function(){var a={};return function(b,c,d){var e=a[b],g;if(!e){e=
new Image;g=doc.createElement("canvas");e.src=b;g.width=c;g.height=d;g.getContext("2d").drawImage(e,0,0);e=a[b]=g.toDataURL()}return e}}(),Ea:h.Rb.prototype.Ea,m:function(){var a=this.e.runtimeStyle;this.parent.gb(this.ua);a.borderColor=a.borderStyle=a.borderWidth=""}});h.ob=function(){function a(f,k,m){f.attachEvent(k,m)}function b(f){function k(){if(!J){var z,E,G=h.Ba,N=f.currentStyle,M=N.getAttribute(d)==="true";H=N.getAttribute(e);H=G>7?H!=="false":H==="true";if(!F){F=1;f.runtimeStyle.zoom=1;
N=f;for(var O=1;N=N.previousSibling;)if(N.nodeType===1){O=0;break}if(O)f.className+=" "+h.nb+"first-child"}u.cb();if(M&&(E=u.o())&&(z=doc.documentElement||doc.body)&&(E.y>z.clientHeight||E.x>z.clientWidth||E.y+E.f<0||E.x+E.h<0)){if(!L){L=1;h.pb.ka(k)}}else{J=1;L=F=0;h.pb.ib(k);if(G===9){B={w:new h.Qb(f),q:new h.Sb(f),C:new h.Tb(f)};D=[B.w,B.q];A=new h.Kc(f,u,B);z=[new h.Ic(f,u,B,A),new h.Jc(f,u,B,A)]}else{B={w:new h.Qb(f),C:new h.Tb(f),q:new h.Sb(f),D:new h.mb(f),fa:new h.Ec(f),Nb:new h.Qc(f)};D=
[B.w,B.C,B.q,B.D,B.fa,B.Nb];A=new h.Nc(f,u,B);z=[new h.Dc(f,u,B,A),new h.Bc(f,u,B,A),new h.Cc(f,u,B,A),new h.Rb(f,u,B,A)];f.tagName==="IMG"&&z.push(new h.Lc(f,u,B,A));A.ad=z}y=[A].concat(z);if(z=f.currentStyle.getAttribute(h.R+"watch-ancestors")){C=[];z=parseInt(z,10);E=0;for(M=f.parentNode;M&&(z==="NaN"||E++<z);){C.push(M);M.attachEvent("onpropertychange",v);M.attachEvent("onmouseenter",q);M.attachEvent("onmouseleave",p);M=M.parentNode}}if(H){h.Ma.ka(l);h.Ma.Nd()}l(1)}if(!K){K=1;G<9&&a(f,"onmove",
m);f.attachEvent("onresize",m);f.attachEvent("onpropertychange",o);f.attachEvent("onmouseenter",q);f.attachEvent("onmouseleave",p);h.Oa.ka(m);h.S.ka(w)}u.hb()}}function m(){u&&u.wd()&&l()}function l(z){if(!I)if(J){var E,G=y.length;t();for(E=0;E<G;E++)y[E].Ea();if(z||u.Kd())for(E=0;E<G;E++)y[E].jb();if(z||u.Pd())for(E=0;E<G;E++)y[E].Lb();A.$a();n()}else F||k()}function o(){var z,E=y.length,G;z=event;if(!I&&!(z&&z.propertyName in j))if(J){t();for(z=0;z<E;z++)y[z].Ea();for(z=0;z<E;z++){G=y[z];G.Eb||
G.jb();G.N()&&G.Kb()}A.$a();n()}else F||k()}function r(){if(f)f.className+=g}function s(){if(f)f.className=f.className.replace(i,"")}function q(){setTimeout(r,0)}function p(){setTimeout(s,0)}function v(){var z=event.propertyName;if(z==="className"||z==="id")o()}function t(){u.cb();for(var z=D.length;z--;)D[z].cb()}function n(){for(var z=D.length;z--;)D[z].hb();u.hb()}function w(){if(K){if(C)for(var z=0,E=C.length,G;z<E;z++){G=C[z];G.detachEvent("onpropertychange",v);G.detachEvent("onmouseenter",q);
G.detachEvent("onmouseleave",p)}f.detachEvent("onmove",l);f.detachEvent("onresize",l);f.detachEvent("onpropertychange",o);f.detachEvent("onmouseenter",q);f.detachEvent("onmouseleave",p);h.S.ib(w);K=0}}function x(){if(!I){var z,E;w();I=1;if(y){z=0;for(E=y.length;z<E;z++){y[z].cc=1;y[z].m()}}H&&h.Ma.ib(l);h.Oa.ib(l);y=u=B=D=C=f=null}}var y,A,u=new V(f),B,D,C,F,J,K,L,I,H;this.Bd=k;this.update=l;this.m=x;this.md=f}var c={},d=h.R+"lazy-init",e=h.R+"poll",g=" "+h.nb+"hover",i=new RegExp("\\b"+h.nb+"hover\\b",
"g"),j={background:1,bgColor:1,display:1};b.ud=function(f){var k=h.p.Aa(f);return c[k]||(c[k]=new b(f))};b.m=function(f){f=h.p.Aa(f);var k=c[f];if(k){k.m();delete c[f]}};b.hd=function(){var f=[],k;if(c){for(var m in c)if(c.hasOwnProperty(m)){k=c[m];f.push(k.md);k.m()}c={}}return f};return b}();h.supportsVML=h.vc;h.attach=function(a){h.Ba<10&&h.vc&&h.ob.ud(a).Bd()};h.detach=function(a){h.ob.m(a)}};
})();